// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzuhnakggjakxwrjyiqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6dWhuYWtnZ2pha3h3cmp5aXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTc1MjcsImV4cCI6MjA3MDkzMzUyN30.mvUkOkQIgViWaKENmbxU2DrA5Zn6CCQItA8jJBSbEy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});